package com.example.footu.utils

const val ITEMS_PICKED = "ITEMS_PICKED"
const val ANDROID = "android"
const val DIMEN = "dimen"
const val STATUS_BAR_HEIGHT = "status_bar_height"
const val CHANNEL_ID = "CHANNEL_ID"
const val PERMISSIONS_REQUEST_CODE = 111
const val SHIPPER_ID = "SHIPPER_ID"
const val LOCATION_PERMISSION_REQUEST_CODE = 999
const val ORDER_TYPE = "ORDER_TYPE"
const val ITEM_TYPE = "ITEM_TYPE"
const val ORDER_TYPE_DIALOG = "ORDER_TYPE_DIALOG"
const val ITEMS_CHOOSE = "ITEMS_CHOOSE"
const val ITEMS_CHOOSE_ACTION = "ITEMS_CHOOSE_ACTION"
const val OTHER_USER_ID = "OTHER_USER_ID"
const val ID_CHANNEL_LOCATION_SOCKET = "ID_CHANNEL_LOCATION_SOCKET"
const val PREF_ACCESS_TOKEN = "PREF_ACCESS_TOKEN"
const val PREF_REFRESH_TOKEN = "PREF_REFRESH_TOKEN"
const val APP_ID = 170453157L
const val APP_SIGN = "a68d4d145f2b669973f6596306b74c3a05c670b0b6298466b220a9349d073995"
const val REQUEST_CAMERA_PERMISSION = 100
const val REQUEST_IMAGE_CAPTURE = 101
