package com.example.footu.utils


const val ITEMS_PICKED = "ITEMS_PICKED"
const val ANDROID = "android"
const val DIMEN = "dimen"
const val STATUS_BAR_HEIGHT = "status_bar_height"
const val CHANNEL_ID = "CHANNEL_ID"
const val PERMISSIONS_REQUEST_CODE = 111
const val SHIPPER_ID = "SHIPPER_ID"
const val LOCATION_PERMISSION_REQUEST_CODE = 999
const val ORDER_TYPE = "ORDER_TYPE"
const val ITEM_TYPE = "ITEM_TYPE"
const val ORDER_TYPE_DIALOG = "ORDER_TYPE_DIALOG"
const val ITEMS_CHOOSE = "ITEMS_CHOOSE"
const val ITEMS_CHOOSE_ACTION = "ITEMS_CHOOSE_ACTION"
const val OTHER_USER_ID = "OTHER_USER_ID"
const val ID_CHANNEL_LOCATION_SOCKET = "ID_CHANNEL_LOCATION_SOCKET"
const val PREF_ACCESS_TOKEN = "PREF_ACCESS_TOKEN"
const val PREF_REFRESH_TOKEN = "PREF_REFRESH_TOKEN"

